export let PortfolioImg = {
    img1: require('../../Image/Photos/Portfolio/2_4.5x3.jpg'),
    img2: require('../../Image/Photos/Portfolio/16_5x3.jpg'),
    img3: require('../../Image/Photos/Portfolio/15s.jpg'),
    img4: require('../../Image/Photos/Portfolio/4s.jpg'),
    img5: require('../../Image/Photos/Portfolio/5_4.5x3.jpg'),
    img6: require('../../Image/Photos/Portfolio/1_5x3.jpg'),
    img7: require('../../Image/Photos/Portfolio/14_4.5x3.jpg'),
    img8: require('../../Image/Photos/Portfolio/13s.jpg'),
    img9: require('../../Image/Photos/Portfolio/6_4.5x3.jpg'),
    img10: require('../../Image/Photos/Portfolio/18_4.5x3.jpg'),
    img11: require('../../Image/Photos/Portfolio/19s.jpg'),
    img12: require('../../Image/Photos/Portfolio/11_4.5x3.jpg'),
    img13: require('../../Image/Photos/Portfolio/7_4.5x3.jpg'),
    img14: require('../../Image/Photos/Portfolio/20s.jpg'),
    img15: require('../../Image/Photos/Portfolio/17_4.5x3.jpg'),
    img16: require('../../Image/Photos/Portfolio/21_4.5x3.jpg'),
    img17: require('../../Image/Photos/Portfolio/22_4.5x3.jpg'),
    img18: require('../../Image/Photos/Portfolio/3_4.5x3.jpg'),
    img19: require('../../Image/Photos/Portfolio/10_4.5x3.jpg'),
    img20: require('../../Image/Photos/Portfolio/8_4.5x3.jpg'),
    img21: require('../../Image/Photos/Portfolio/9s.jpg'),
    img22: require('../../Image/Photos/Portfolio/12_4.5x3.jpg'),
}

